version: '3'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  app-one:
    build: ./app-one
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    volumes:
      - ./app-one:/usr/src/app
