version: '3.9'

services:
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    # env_file:
    #   - .env
    environment:
      - POSTGRES_USER==${POSTGRES_USER}
      - POSTGRES_PASSWORD==${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD==${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - '5423:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices

  app-one:
    build: ./app-one
    ports:
      - "3001:3000"
    depends_on:
      - db
    volumes:
      - ./db:/usr/src/app/db
    networks:
      - microservices

  auth-service:
    build: ./auth-service
    ports:
      - "3002:3000"
    depends_on:
      - db
    volumes:
      - ./db:/usr/src/app/db
    networks:
      - microservices

  order-service:
    build: ./order-service
    ports:
      - "3003:3000"
    depends_on:
      - db
    volumes:
      - ./db:/usr/src/app/db
    networks:
      - microservices

  product-service:
    build: ./product-service
    ports:
      - "3004:3000"
    depends_on:
      - db
    volumes:
      - ./db:/usr/src/app/db
    networks:
      - microservices

  user-service:
    build: ./user-service
    ports:
      - "3005:3000"
    depends_on:
      - db
    volumes:
      - ./db:/usr/src/app/db
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
